# Syntax configuration for Groovy files.
#
# Regular expressions must conform to the syntax supported by regex-lite.
# https://docs.rs/regex-lite/latest/regex_lite/index.html

[syntax]
name = "Groovy"
files = ['\.(groovy|gradle)$', 'Jenkinsfile']

[tokens]
# Reserved words
'\b(?:abstract|as|assert|boolean|break|byte|case|catch|char|class|const|continue|def|default|do|double|else|enum|extends|false|final|finally|float|for|goto|if|implements|import|in|instanceof|int|interface|long|native|new|null|package|private|protected|public|return|short|static|strictfp|super|switch|synchronized|this|throw|throws|trait|transient|true|try|void|volatile|while)\b' = "orchid-bloom"

# Numbers
'\b[+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b' = "verdant-spring"

# Strings
'"(?:\\(?:.|\n)|[^"\\\n])*"' = "peachy-orange"
"'(?:\\\\(?:.|\\n)|[^'\\\\\n])*'" = "peachy-orange"

# Comments
'//.*$' = "sage-green"
'/\*[\s\S]*?\*/' = "sage-green"
